version: '3.7'

services:
  db:
    build:
      context: ./db
    restart: always
    networks:
      - node
  app:
    build:
      context: ./app
    networks:
      - node
    depends_on:
       - db
    command: dockerize -wait tcp://db:3306 -timeout 20s npm run start
  proxy:
    build:
      context: ./proxy
    ports:
      - 8080:80
    networks:
      - node
    depends_on:
       - app

networks:
  node:
